#!/usr/bin/env python
"""Build NEYTA.app so the thing launches from the Dock without a terminal.

    .venv-neyta/bin/python tools/make_app.py [--to ~/Applications]

What this produces is a **launcher bundle**, not a frozen redistributable. The
bundle committed at the repository root is double-clickable and Dock-pinnable,
and locates the checkout relative to itself. Its executable then runs this
checkout's interpreter. It is deliberately not a PyInstaller build:

  * PySide6-Addons is 332 MB and carries QtWebEngine, which ships its own
    Chromium, its own helper processes and its own framework layout. Freezing
    that correctly is a project in itself and breaks in ways that only show up
    at runtime.
  * NEYTA already depends on two sibling directories that are not Python
    packages — uvr-local's separate 3.11 environment with its torch stack and
    2.7 GB of checkpoints, and samplette-local's SQLite library. Freezing the
    app would not freeze those, so the bundle would still be tied to this
    checkout.

The checked-in bundle moves with the checkout. A bundle built somewhere else
with ``--to`` points back at this checkout instead.
"""

from __future__ import annotations

import argparse
import plistlib
import shlex
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
VENV_PYTHON = ROOT / ".venv-neyta" / "bin" / "python"
APP_NAME = "NEYTA"
BUNDLE_ID = "com.neyta.app"

LAUNCHER = """#!/bin/bash
# Generated by tools/make_app.py — do not edit; regenerate instead.
{root_assignment}
PYTHON="$ROOT/.venv-neyta/bin/python"

fail() {{
  /usr/bin/osascript -e "display alert \\"NEYTA cannot start\\" message \\"$1\\" as critical"
  exit 1
}}

if [ ! -x "$PYTHON" ]; then
  fail "The Python environment is missing from:
$ROOT

If you moved or renamed the project folder, run tools/setup.sh there and then
try again — virtualenvs store absolute paths and do not survive being moved."
fi

cd "$ROOT" || fail "Cannot reach $ROOT"
exec "$PYTHON" -m neyta run
"""


def render_launcher(root: Path | None = None) -> str:
    if root is None:
        assignment = 'ROOT="$(cd "$(dirname "$0")/../../.." && pwd)"'
    else:
        assignment = f"ROOT={shlex.quote(str(root))}"
    return LAUNCHER.format(root_assignment=assignment)


def build_icon(destination: Path) -> bool:
    """Render an .icns from a drawn source, via the system tools.

    Skipped silently when iconutil is unavailable; a bundle with the default
    icon still launches, and refusing to build over a cosmetic step would be
    a poor trade.
    """
    try:
        from PySide6.QtCore import QRectF, Qt
        from PySide6.QtGui import (
            QBrush, QColor, QLinearGradient, QPainter, QPixmap,
        )
        from PySide6.QtWidgets import QApplication
    except ImportError:
        return False

    # QApplication, not QGuiApplication. Painting needs only the latter, but
    # the Qt application object is a process-wide singleton: creating a
    # QGuiApplication here means anything in the same process that later wants
    # a *widget* aborts, because widgets require a QApplication. The test
    # suite found this by building a bundle and then constructing a QWidget.
    app = QApplication.instance() or QApplication([])  # noqa: F841
    iconset = destination.parent / f"{APP_NAME}.iconset"
    if iconset.exists():
        shutil.rmtree(iconset)
    iconset.mkdir(parents=True)

    for size in (16, 32, 64, 128, 256, 512, 1024):
        pixmap = QPixmap(size, size)
        pixmap.fill(Qt.transparent)
        painter = QPainter(pixmap)
        painter.setRenderHint(QPainter.Antialiasing)

        gradient = QLinearGradient(0, 0, size, size)
        gradient.setColorAt(0.0, QColor(38, 42, 58))
        gradient.setColorAt(1.0, QColor(20, 22, 30))
        painter.setBrush(QBrush(gradient))
        painter.setPen(Qt.NoPen)
        radius = size * 0.22
        painter.drawRoundedRect(QRectF(0, 0, size, size), radius, radius)

        # A waveform, since that is what the app is about.
        painter.setPen(Qt.NoPen)
        painter.setBrush(QColor(96, 170, 255))
        bars = 7
        span = size * 0.62
        left = (size - span) / 2
        width = span / (bars * 2 - 1)
        heights = (0.28, 0.55, 0.86, 1.0, 0.72, 0.44, 0.22)
        for i, factor in enumerate(heights):
            height = size * 0.42 * factor
            x = left + i * width * 2
            painter.drawRoundedRect(
                QRectF(x, (size - height) / 2, width, height),
                width / 2, width / 2,
            )
        painter.end()

        for scale, suffix in ((1, ""), (2, "@2x")):
            target = size // scale
            if target < 16 or target > 512:
                continue
            pixmap.scaled(
                target * scale, target * scale,
                Qt.KeepAspectRatio, Qt.SmoothTransformation,
            ).save(str(iconset / f"icon_{target}x{target}{suffix}.png"))

    result = subprocess.run(
        ["iconutil", "-c", "icns", str(iconset), "-o", str(destination)],
        capture_output=True,
    )
    shutil.rmtree(iconset, ignore_errors=True)
    return result.returncode == 0


def build(destination: Path) -> Path:
    bundle = destination / f"{APP_NAME}.app"
    if bundle.exists():
        shutil.rmtree(bundle)

    macos = bundle / "Contents" / "MacOS"
    resources = bundle / "Contents" / "Resources"
    macos.mkdir(parents=True)
    resources.mkdir(parents=True)

    executable = macos / APP_NAME
    launcher_root = None if destination == ROOT else ROOT
    executable.write_text(render_launcher(launcher_root), "utf-8")
    executable.chmod(0o755)

    info = {
        "CFBundleName": APP_NAME,
        "CFBundleDisplayName": APP_NAME,
        "CFBundleIdentifier": BUNDLE_ID,
        "CFBundleVersion": "1.0",
        "CFBundleShortVersionString": "1.0",
        "CFBundleExecutable": APP_NAME,
        "CFBundlePackageType": "APPL",
        "LSMinimumSystemVersion": "13.0",
        # Without this the launcher script shows a Dock icon for the shell
        # and the app never takes focus properly.
        "LSBackgroundOnly": False,
        "NSHighResolutionCapable": True,
        "NSRequiresAquaSystemAppearance": False,
    }
    if build_icon(resources / f"{APP_NAME}.icns"):
        info["CFBundleIconFile"] = f"{APP_NAME}.icns"

    (bundle / "Contents" / "Info.plist").write_bytes(plistlib.dumps(info))

    # Ad-hoc signature. Not distribution signing — it stops Gatekeeper
    # complaining about an unsigned bundle on this machine, nothing more.
    subprocess.run(
        ["codesign", "--force", "--deep", "--sign", "-", str(bundle)],
        capture_output=True,
    )
    return bundle


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="make_app")
    parser.add_argument(
        "--to", default=str(ROOT),
        help="where to write NEYTA.app (default: the project folder)",
    )
    args = parser.parse_args(argv)

    destination = Path(args.to).expanduser().resolve()
    destination.mkdir(parents=True, exist_ok=True)
    bundle = build(destination)

    print(f"built {bundle}")
    print(f"  launches: {VENV_PYTHON} -m neyta run")
    relationship = "moves with this checkout" if destination == ROOT else f"tied to: {ROOT}"
    print(f"  {relationship}")
    print("\nDrag it to the Dock. If you move the project folder, rerun "
          "tools/setup.sh.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
